apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-calendar-config
  namespace: booking-calendar
data:
  PORT: "8080"
  GOOGLE_CALENDAR_ID: "075fc8ead0cabfe9bee641306e905d712f052131f84960ab83d386556b72156b@group.calendar.google.com"
  GOOGLE_CALENDAR_TIMEZONE: "Asia/Bangkok"
  GOOGLE_SERVICE_ACCOUNT_JSON_FILE: "/app/secrets/service-account.json"
