apiVersion: v1
kind: Service
metadata:
  name: booking-calendar
  namespace: booking-calendar
spec:
  selector:
    app: booking-calendar
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
